config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  resources :users
  
  get 'notes/index' 
  get 'notes/class1'
  get 'notes/class1Notes'
   get 'notes/class2Notes'
  
  resources :notes do
    resources :comments
  end
  
  root 'notes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :note
  validates :commenter, presence: true
    validates :body, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true
    validates :course, presence: true, length: {minimum: 8 }
    validates :text, presence: true, length: {minimum: 5 }
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :notes
    #VALID_EMAIL_REGEX = /A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    #VALID_EMAIL_REGEX = [a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+
    
    VALID_EMAIL_REGEX = /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\z/
     
    before_save { self.email = email.downcase }
    
    validates :name,
        presence: true,
        length: { maximum: 50 }
    
    validates :email,
        presence: true,
        length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        
    validates :password,
        presence: true,
        length: { minimum: 6 }
        
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end           
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @note = Note.find(params[:note_id])
        @comment = @note.comments.create(comment_params)
        redirect_to note_path(@note)
    end
    
    def destroy
        @note = Note.find(params[:note_id])
        @comment = @note.comments.find(params[:id])
        @comment.destroy
        redirect_to note_path(@note)
    end
    
    
    
    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    
    def class1
        @notes = Note.all
    end
    
    def class1Notes
        @notes = Note.all
    end

    def class2Notes
        @notes = Note.all
    end

    def show 
         @note = Note.find(params[:id])
    end
    
    def new
        @note = Note.new
    end
    
    def create
         @note = Note.new(note_params)
         @note.user = current_user
         
        if @note.save
            redirect_to @note
        else
            render 'new'
        end
    end
    
    def edit
        @note = Note.find(params[:id])
    end
    
    def update 
        @note = Note.find(params[:id]) 
        
        if @note.update(note_params) 
            redirect_to @note 
        else 
                render 'edit' 
        end 
    end
    
    def destroy 
        @note = Note.find(params[:id])
        @note.destroy
        
        redirect_to notes_class1_path
    end
        
end

private 
    def note_params
        params.require(:note).permit(:title, :course, :text)

    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "You're in!"
      
    else
      flash.now[:alert] = "Email or ID is invalid"
      render "new"
    end
    
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "And you're out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>
 
<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>


<p>
  <%= link_to 'Delete Comment', [comment.note, comment],
                                method: :delete,
                                data: { confirm: 'Are you sure you want to delete?' } %></td>



</p>

app/views/comments/_form.html.erb
<%= form_for([@note, @note.comments.build]) do |f| %>

 <% if @note.errors.any? %>
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    
  <% end %>
  
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
 
  <% if @note.errors.any? %>
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited
        this note from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :course %> <i><strong>(Enter course as XXXX1234)</strong></i><br>
    <%= f.text_field :course %>
  </p>

  <p>
    <%= f.label :note %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/notes/class1.html.erb
<section>
    <center><h1 id="idk">Add Note</h1></center>

<center>
    <button id="addNote"><%= link_to '+', new_note_path %></button>
<br>
</center>
</section>
<br>
<section>
<h1>My Notes</h1>
<center>
    <table>
    <tr>
        <th id="text1">Title</th>
    </tr>
    <% @notes.each do |note| %>
    <% if note.user_id == current_user.id %>
    <tr>
        <td id="text2"><%= note.title %></td>
        <td><div id="buttonCRUD"><%= link_to 'Show', note_path(note) %></div></td>
        <td><div id="buttonCRUD"><%= link_to 'Edit', edit_note_path(note) %></div></td>
        <td><div id="buttonCRUD"><%= link_to 'Delete', 
                                    note_path(note),
                                    method: :delete,
                                    data: {confirm: 'Sure you want to toss it?'} %></div></td>
        
    </tr>
    <% end %>
    <% end %>
</table>
</center>

<br>
<br>
<br>
<button id= 'button' name="homealone"><%= link_to 'Home', notes_index_path %></button>
<br>
</section>

app/views/notes/class1Notes.html.erb
<section>
<center><h1>Software Engineering</h1></center>
<center><h2>ITSC-3155</h2></center>
<br>
<br>
    <center><table>
    <tr>
        <th id="text1">Note Title</th>
    </tr>
    <% @notes.each do |note| %>
    <% if note.course == 'ITSC3155' %>
    <tr>
        <td id="text2"><%= note.title %></td>
        <td><div id="buttonCRUD"><%= link_to 'View', note_path(note) %></div></td>
    </tr>
    <% end %>
    <% end %>
<br>
</table>
</center>

<br>
<button id = 'button' name='home'><%= link_to 'Back', notes_index_path %></button>
</section>

app/views/notes/class2Notes.html.erb
<section>
<center><h1>Software Arch & Design</h1></center>
<center><h2>ITIS-3310</h2></center>
<br>
<br>
    <center><table>
    <tr>
        <th id="text1">Note Title</th>
    </tr>
    <% @notes.each do |note| %>
    <% if note.course == 'ITIS3310' %>
    <tr>
        <td id="text2"><%= note.title %></td>
        <td><div id="buttonCRUD"><%= link_to 'View', note_path(note) %></div></td>
    </tr>
    <% end %>
    <% end %>
<br>
</table>
</center>

<br>
<button id = 'button' name='home'><%= link_to 'Back', notes_index_path %></button>
</section>

app/views/notes/edit.html.erb
<section><h1>Edit</h1>
 
<%= render 'form' %>
 
<button id = 'button'><%= link_to 'Home', notes_index_path %></button>
</section>

app/views/notes/index.html.erb
<!--Why is this page so wide now?---->
<section>
<h1 id="welcome">cNotes</h1>
<h2><i>Create and share notes with your class</i></h2>
<br>
    <% if current_user %>
    <h3 class="toCenter">Hi, <%= current_user.name %></h3>
    <button id = 'button' name="SE"><%= link_to "Log Out", logout_path %></button></div><!--why is the layout of the text like that? The out should be on the same line as log-->
    <p>---------------------------------------------------------------</p>
    
    <h3 class="toCenter">Visit your dashboard for more</h3>
    <p>
    <button id = 'button' name="myDashboard"><%= link_to 'My Dashboard', notes_class1_path %></button>
    <br>
    <% else %>
    <h3 id="register">Sign up or Login to share your notes</h3>
        <button id = 'button'><%= link_to "Sign Up!", signup_path %></button> 
        <button id = 'button'><%= link_to "Log In", login_path %></button>
    <% end %>
</p>

<p>---------------------------------------------------------------</p>
      <h3 class="toCenter">Available Classes</h3>
      <button id = 'button' name="SE"><%= link_to 'ITSC-3155', notes_class1Notes_path %></button>
    <button id = 'button' name="SE"><%= link_to 'ITIS-3310', notes_class2Notes_path %></button>

</p>
</section>
    

app/views/notes/new.html.erb
<section><h1>New Note</h1>
<p><h3>Please add your new note below and just click "Create Note", its that simple</h3></p>
<br>
Make sure to include a title for your note! Notes must be atleast 5 characters so be sure to include as much as you can.
<br>
Remember you're sharing this note with your classmates so make it count!
<br>
<%= render 'form' %>

<button id= 'button'><%= link_to 'Back', notes_class1_path %></button>
</section>
  

app/views/notes/show.html.erb
  <h1 id="title">
  <%= @note.title %>
</h1>
 
<p id="note"><!--I made the background of this white. It makes it look stupid with so little text, but if you imagine it with a whole
bunch of text like a class' notes would be it seems ok. signed Zachary Martin--->
  <%= @note.text %>
</p>

<%if current_user %>
<section>
 <h2>Have feedback?</h2>
<%= form_for([@note, @note.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :commenter %>
  </p>
  
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>
  <button id= 'button' name="homealone"><%= link_to 'Back', notes_index_path %></button>
  </section>
  
  <section>
<h2>Collaborate</h2>
<br>
<% @note.comments.each do |comment| %>

  <p>
    <strong>User:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>-----------------------------------</p>
<% end %>
</section>
  
      <% else %>
    
    <section>
    <h2 id="register">Only registered users may make comments. Please sign up or login for full access!</h2>
    
        <button id = 'button'><%= link_to "Sign Up", signup_path %></button>
        <button id = 'button'><%= link_to "Log In", login_path %></button>
        <button id= 'button' name="homealone"><%= link_to 'Back', notes_index_path %></button>
        </section>
    <% end %>
    

app/views/users/_form.html.erb
  <% if user.errors.any? %>
    <section>
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </section>
  <% end %>
  

<%= form_with(model: user, local: true) do |form| %>

    <%= form.label :name %>
    <%= form.text_field :name %>
  
    <br>
    <br>
    <%= form.label :email %>
    <%= form.text_field :email %>


    <br>
    <br>
    <%= form.label :password %>
    <%= form.password_field :password %>


    <br>
    <br>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    
    <br>
    <br>
    <%= form.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<section>
<h1>Lets get started</h1>

<%= render 'form', user: @user %>
<br>
<button id = 'button' name='home'><%= link_to 'Back', notes_index_path %></button>
</section>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', notes_path %>

app/views/welcome/login.html.erb
<section>

    <h1>cNotes</h1>
    <h2>Create and share notes with your classmates</h2>
    <br>
   <button id='button'><%= link_to 'Continue', controller: 'notes' %></button>

   <button id = 'button' name='home'><%= link_to 'Back', notes_index_path %></button>

</section>

<!---more git branch testing -->